"""
seed_ayurveda_50.py
====================
Seeds 50 entries: Ayurvedic herbs, foods, vegetables, fruits, spices.
Each entry includes: nutritional data, drug interactions, dosing, dosha, health benefits.

"""
import sqlite3, json, logging
from db_config import DB_PATH

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
log = logging.getLogger(__name__)

AYURVEDA_DATA = [
    # ─── AYURVEDIC HERBS (15) ──────────────────────────────────────────────
    {
        "name": "Turmeric (Haridra)",
        "local_names": json.dumps(["Haridra","Haldi","Curcuma","Manjal"]),
        "entry_type": "Ayurveda",
        "category": "Anti-inflammatory / Antioxidant",
        "botanical_name": "Curcuma longa",
        "plant_family": "Zingiberaceae",
        "parts_used": "Rhizome (root)",
        "rasa": "Tikta (bitter), Katu (pungent)",
        "virya": "Ushna (hot)",
        "vipaka": "Katu (pungent)",
        "dosha_effect": "Balances Kapha and Vata; may aggravate Pitta in excess",
        "traditional_uses": json.dumps(["Anti-inflammatory","Wound healing","Liver protection","Digestive aid","Skin conditions","Joint pain"]),
        "modern_evidence": "Curcumin (active): COX-2 inhibitor, NF-κB modulation, antioxidant. 8 RCTs show modest benefit in OA. Limited bioavailability (use piperine/lipid formulations).",
        "indications": json.dumps(["Osteoarthritis","IBD","Metabolic syndrome","Depression (adjunct)","Fatty liver"]),
        "contraindications": "Gallstones (stimulates bile), high doses in pregnancy, peptic ulcers",
        "calories_per_100g": 354.0,
        "protein_g": 7.83,
        "carbs_g": 64.93,
        "fat_g": 9.88,
        "fiber_g": 21.1,
        "key_nutrients": json.dumps({"curcumin": "2-5%", "manganese": "19.8mg", "iron": "41.4mg", "vit_B6": "1.8mg"}),
        "drug_interactions": json.dumps(["Warfarin (potentiates anticoagulation — monitor INR)","Antiplatelet drugs (additive)","Diabetes drugs (additive hypoglycaemia)","Chemotherapy (CYP3A4 interaction — discuss with oncologist)"]),
        "interactions_detail": "Curcumin inhibits CYP3A4, CYP2C9, P-gp. Monitor INR if on warfarin. May potentiate diabetes medications.",
        "dose_adult": "500-2000mg curcumin/day (with piperine 20mg for absorption). Powder: 1-3g daily in warm milk.",
        "dose_pediatric": "Not well established; use culinary amounts only (<1 year avoid)",
        "dose_geriatric": "500-1000mg/day; well tolerated; monitor anticoagulants",
        "preparation": "Golden milk: 1 tsp turmeric + warm milk + black pepper. Capsules with bioperine. Paste for topical wounds.",
        "safety_notes": "GRAS (generally recognised as safe) at culinary doses. Supplement doses may interact with anticoagulants.",
        "glycemic_index": "Low (not a significant carbohydrate source)",
        "diet_category": "Anti-inflammatory, Diabetic-friendly, Cardiac-friendly",
        "health_benefits": json.dumps(["Anti-inflammatory","Antioxidant","Liver protective","Neuroprotective","Antimicrobial","Immunomodulatory"]),
    },
    {
        "name": "Ashwagandha (Withania)",
        "local_names": json.dumps(["Ashwagandha","Indian Ginseng","Withania somnifera","Asgandh"]),
        "entry_type": "Ayurveda",
        "category": "Adaptogen / Nervine",
        "botanical_name": "Withania somnifera",
        "plant_family": "Solanaceae",
        "parts_used": "Root, leaves",
        "rasa": "Tikta (bitter), Kashaya (astringent), Madhura (sweet)",
        "virya": "Ushna (hot)",
        "vipaka": "Madhura (sweet)",
        "dosha_effect": "Balances Vata and Kapha; neutral to Pitta",
        "traditional_uses": json.dumps(["Stress reduction","Fatigue","Anxiety","Male fertility","Muscle strength","Hypothyroidism support"]),
        "modern_evidence": "Multiple RCTs show significant cortisol reduction. Improves VO2 max. Testosterone increase in subfertile males. KSM-66 and Sensoril extracts most studied.",
        "indications": json.dumps(["Stress/anxiety","Fatigue syndrome","Subclinical hypothyroidism","Athletic performance","Male infertility"]),
        "contraindications": "Pregnancy (uterine stimulant), autoimmune disease, thyroid hyperactivity, nightshade allergy",
        "key_nutrients": json.dumps({"withanolides": "2.5-5% (standardised)", "iron": "3.3mg/100g", "alkaloids": "present"}),
        "drug_interactions": json.dumps(["Thyroid medication (may enhance T3/T4 — monitor TSH)","Immunosuppressants (may counteract)","Sedatives/BZDs (additive CNS depression)","Diabetes drugs (hypoglycaemia)","Antihypertensives (additive)"]),
        "dose_adult": "300-600mg standardised root extract (5% withanolides) BD. Raw powder: 3-6g/day in milk.",
        "dose_pediatric": "Not recommended <12 years",
        "dose_geriatric": "300mg BD; well tolerated; beneficial for muscle strength",
        "safety_notes": "Generally safe. Rare: thyrotoxicosis (excess), hepatotoxicity (high dose). Avoid in pregnancy.",
        "diet_category": "Adaptogen, Stress-relief",
        "health_benefits": json.dumps(["Cortisol reduction","Muscle strength","Testosterone support","Anti-anxiety","Anti-fatigue","Thyroid modulation"]),
    },
    {
        "name": "Brahmi (Bacopa)",
        "local_names": json.dumps(["Brahmi","Water Hyssop","Bacopa","Jalanimba"]),
        "entry_type": "Ayurveda",
        "category": "Nootropic / Nervine",
        "botanical_name": "Bacopa monnieri",
        "plant_family": "Plantaginaceae",
        "parts_used": "Whole plant",
        "rasa": "Tikta (bitter), Kashaya (astringent)",
        "virya": "Sheeta (cool)",
        "dosha_effect": "Balances all three doshas (tridoshic); especially calms Pitta",
        "traditional_uses": json.dumps(["Memory enhancement","Anxiety","Epilepsy","Dementia","ADHD","Depression"]),
        "modern_evidence": "Multiple RCTs: improves memory acquisition and retention (delayed memory >12 weeks). Antioxidant. Cholinesterase inhibition. AChE inhibitor.",
        "indications": json.dumps(["Memory enhancement","ADHD (adjunct)","Anxiety","Age-related cognitive decline"]),
        "contraindications": "Pregnancy (uterine stimulant), bradycardia (cholinergic effect), hypothyroidism",
        "drug_interactions": json.dumps(["Acetylcholinesterase inhibitors (donepezil — additive)","Calcium channel blockers (additive bradycardia)","Phenytoin (may reduce levels)","Thyroid medications"]),
        "dose_adult": "300-450mg standardised extract (20% bacosides) once daily. Best taken with food (fat-soluble). 12-week trial minimum.",
        "safety_notes": "Generally safe. GI side effects (nausea, cramps) common — take with food. May cause bradycardia.",
        "diet_category": "Nootropic, Mental health",
        "health_benefits": json.dumps(["Memory enhancement","Anti-anxiety","Neuroprotective","Antioxidant","Anti-epileptic (adjunct)"]),
    },
    {
        "name": "Triphala",
        "local_names": json.dumps(["Triphala","Three fruits formula","Trifala"]),
        "entry_type": "Ayurveda",
        "category": "Digestive Tonic / Antioxidant",
        "botanical_name": "Emblica officinalis + Terminalia chebula + Terminalia bellirica",
        "parts_used": "Dried fruits (3 combined)",
        "rasa": "All 5 tastes (lacks only salt)",
        "virya": "Neutral",
        "dosha_effect": "Tridoshic — balances all three doshas",
        "traditional_uses": json.dumps(["Constipation","Colon cleansing","Eye health","Antioxidant","Immune support","Oral health"]),
        "modern_evidence": "Antioxidant (ORAC score very high). Mild laxative (anthraquinones). Anti-diabetic properties. Anti-inflammatory. Prebiotic effects.",
        "drug_interactions": json.dumps(["Warfarin (potentiates — vitamin K content)","Iron supplements (tannins reduce absorption — 2h gap)","Metformin (additive blood sugar lowering)"]),
        "dose_adult": "500mg-1g BD or 1-2 tsp powder in warm water at bedtime",
        "dose_pediatric": "250-500mg once daily (>5 years)",
        "safety_notes": "Laxative effect at high doses. Avoid in pregnancy (stimulant laxative component).",
        "diet_category": "Digestive health, Antioxidant",
        "health_benefits": json.dumps(["Bowel regularity","Antioxidant","Prebiotic","Anti-inflammatory","Oral health","Eye health"]),
    },
    {
        "name": "Neem (Azadirachta)",
        "local_names": json.dumps(["Neem","Margosa","Nimtree","Nim"]),
        "entry_type": "Ayurveda",
        "category": "Antimicrobial / Blood purifier",
        "botanical_name": "Azadirachta indica",
        "plant_family": "Meliaceae",
        "parts_used": "Leaves, bark, seeds, oil",
        "rasa": "Tikta (bitter)",
        "virya": "Sheeta (cool)",
        "dosha_effect": "Balances Pitta and Kapha",
        "traditional_uses": json.dumps(["Skin diseases","Malaria","Diabetes","Dental care","Anti-parasitic","Blood purification"]),
        "modern_evidence": "Azadirachtin: antimalarial, anti-fungal, insecticidal. Nimbidiol: anti-inflammatory. Topical antibacterial for dental/skin use well-established.",
        "contraindications": "Pregnancy (abortifacient), infertility treatment, children <12 (Reye's-like syndrome reported), organ transplant",
        "drug_interactions": json.dumps(["Antidiabetics (additive blood sugar lowering)","Immunosuppressants (counteract)","Lithium (may increase levels)"]),
        "dose_adult": "Leaf powder: 1-4g daily. Neem oil: topical only. Bark decoction: 5-10mL BD.",
        "safety_notes": "Topical use safe. Internal use: avoid high doses in children and pregnancy. Hepatotoxicity rare but reported at high doses.",
        "diet_category": "Antimicrobial, Diabetic-friendly",
        "health_benefits": json.dumps(["Antimicrobial","Anti-inflammatory","Dental health","Blood sugar control","Antiparasitic"]),
    },
    {
        "name": "Shatavari (Asparagus racemosus)",
        "local_names": json.dumps(["Shatavari","Wild Asparagus","Satavar"]),
        "entry_type": "Ayurveda",
        "category": "Female Tonic / Adaptogen",
        "botanical_name": "Asparagus racemosus",
        "plant_family": "Asparagaceae",
        "parts_used": "Root",
        "rasa": "Madhura (sweet), Tikta (bitter)",
        "virya": "Sheeta (cool)",
        "dosha_effect": "Balances Vata and Pitta",
        "traditional_uses": json.dumps(["Female reproductive health","Lactation support","Menopausal symptoms","Gastric ulcers","Immune support"]),
        "modern_evidence": "Steroidal saponins (shatavarin I-IV): prolactin stimulation (galactagogue), oestrogen-modulating, gastric mucosal protection.",
        "contraindications": "Asparagus allergy, oestrogen-sensitive cancers (theoretical), fluid retention conditions",
        "drug_interactions": json.dumps(["Diuretics (counteract fluid retention effect)","Oestrogen therapy (additive or conflicting)","Lithium (may alter clearance)"]),
        "dose_adult": "500mg standardised extract BD. Powder: 3-6g in warm milk daily.",
        "safety_notes": "Generally well tolerated. Avoid in oestrogen-sensitive conditions.",
        "diet_category": "Women's health, Lactation support",
        "health_benefits": json.dumps(["Galactagogue (milk production)","Hormonal balance","Gastric protection","Immune support","Adaptogen"]),
    },
    {
        "name": "Guduchi (Giloy)",
        "local_names": json.dumps(["Guduchi","Giloy","Tinospora","Amrita"]),
        "entry_type": "Ayurveda",
        "category": "Immunomodulator",
        "botanical_name": "Tinospora cordifolia",
        "plant_family": "Menispermaceae",
        "parts_used": "Stem, root",
        "rasa": "Tikta (bitter), Kashaya (astringent)",
        "virya": "Ushna (hot)",
        "dosha_effect": "Balances all three doshas — Rasayana (rejuvenating)",
        "traditional_uses": json.dumps(["Fever","Immunity","Dengue fever","Rheumatoid arthritis","Diabetes","Chronic cough"]),
        "modern_evidence": "Tinosporin, Berberine: immunostimulant (macrophage activation), antipyretic, anti-inflammatory, hypoglycaemic.",
        "contraindications": "Pregnancy, autoimmune conditions (immune stimulation), before surgery (immunostimulant)",
        "drug_interactions": json.dumps(["Immunosuppressants (counteract)","Antidiabetics (hypoglycaemia)","Hypotensives (additive)"]),
        "dose_adult": "300-500mg extract BD or fresh stem juice 20-30mL daily",
        "safety_notes": "Generally safe. Rare cases of liver injury reported (possibly contaminated products).",
        "diet_category": "Immune support",
        "health_benefits": json.dumps(["Immunomodulation","Antipyretic","Anti-inflammatory","Anti-diabetic","Hepatoprotective"]),
    },
    {
        "name": "Triphala Guggulu",
        "local_names": json.dumps(["Guggulu","Guggul","Commiphora","Indian Bdellium"]),
        "entry_type": "Ayurveda",
        "category": "Lipid-lowering / Anti-arthritic",
        "botanical_name": "Commiphora mukul",
        "parts_used": "Resin (gum)",
        "rasa": "Tikta (bitter), Katu (pungent)",
        "virya": "Ushna (hot)",
        "dosha_effect": "Balances Kapha and Vata",
        "traditional_uses": json.dumps(["High cholesterol","Obesity","Arthritis","Thyroid dysfunction","Inflammation"]),
        "modern_evidence": "Guggulsterone: farnesoid X receptor (FXR) antagonist → affects bile acid metabolism/cholesterol. Clinical trials inconsistent. May lower total cholesterol and LDL modestly.",
        "drug_interactions": json.dumps(["Warfarin (anticoagulant potentiation)","Propranolol/diltiazem (reduces bioavailability of these drugs)","Thyroid medications (monitor TSH)"]),
        "dose_adult": "500mg guggulsterone extract BD-TDS with meals",
        "safety_notes": "May cause rash, diarrhoea. Affects drug absorption of co-administered medicines. Avoid in pregnancy.",
        "diet_category": "Lipid management",
        "health_benefits": json.dumps(["Cholesterol lowering","Anti-arthritic","Thyroid support","Anti-obesity","Anti-inflammatory"]),
    },
    {
        "name": "Amalaki (Indian Gooseberry)",
        "local_names": json.dumps(["Amla","Amalaki","Indian Gooseberry","Phyllanthus emblica"]),
        "entry_type": "Ayurveda",
        "category": "Antioxidant / Vitamin C source",
        "botanical_name": "Phyllanthus emblica",
        "parts_used": "Fruit",
        "rasa": "Amla (sour), Madhura (sweet), Kashaya (astringent)",
        "virya": "Sheeta (cool)",
        "dosha_effect": "Balances all three doshas (Tridoshic)",
        "traditional_uses": json.dumps(["Immune support","Skin health","Hair growth","Digestion","Rejuvenation","Antioxidant"]),
        "modern_evidence": "Highest natural Vitamin C source (~600-700mg/100g). Tannins are heat-stable. Polyphenols: ellagic acid, gallic acid. Clinical benefit in dyslipidaemia, diabetes, non-alcoholic fatty liver.",
        "calories_per_100g": 44.0,
        "protein_g": 0.9,
        "carbs_g": 10.2,
        "fat_g": 0.6,
        "fiber_g": 4.3,
        "key_nutrients": json.dumps({"vitamin_C": "600-700mg", "tannins": "high", "gallic_acid": "present"}),
        "drug_interactions": json.dumps(["Warfarin (may potentiate — monitor INR)","Iron supplements (enhances absorption — positive interaction)","Antidiabetics (additive)"]),
        "dose_adult": "1-3 fresh fruits/day. Juice: 10-20mL. Powder: 3-6g. Extract: 500-1000mg BD",
        "dose_pediatric": "1 fruit/day or juice 5-10mL",
        "diet_category": "Antioxidant, Diabetic-friendly, Immune support",
        "health_benefits": json.dumps(["Vitamin C richest food","Antioxidant","Hair & skin health","Cholesterol lowering","Digestive tonic","Hepatoprotective"]),
    },
    {
        "name": "Shankhpushpi",
        "local_names": json.dumps(["Shankhpushpi","Convolvulus pluricaulis"]),
        "entry_type": "Ayurveda",
        "category": "Nootropic / Anxiolytic",
        "botanical_name": "Convolvulus pluricaulis",
        "parts_used": "Whole plant",
        "rasa": "Kashaya (astringent), Tikta (bitter), Madhura (sweet)",
        "virya": "Sheeta (cool)",
        "dosha_effect": "Balances Vata and Pitta",
        "traditional_uses": json.dumps(["Memory enhancement","Anxiety","Insomnia","Hypothyroidism","Migraine"]),
        "modern_evidence": "Scopoletin, flavonoids: GABA modulation, acetylcholinesterase inhibition, reduced cortisol, thyroid hormone modulation (T3/T4 stimulation).",
        "contraindications": "Hyperthyroidism (stimulates thyroid), pregnancy",
        "drug_interactions": json.dumps(["Phenytoin (reduces phenytoin levels — significant interaction; avoid or monitor closely)","Thyroid medications (additive)","Sedatives (additive)"]),
        "dose_adult": "250-500mg extract BD or fresh juice 5-10mL BD",
        "safety_notes": "Avoid with phenytoin — significantly reduces phenytoin plasma levels (clinical case reports).",
        "diet_category": "Nootropic, Mental health",
        "health_benefits": json.dumps(["Memory enhancement","Anti-anxiety","Thyroid support","Neuroprotective","Insomnia relief"]),
    },
    {
        "name": "Moringa (Drumstick)",
        "local_names": json.dumps(["Moringa","Drumstick","Sahjan","Malunggay","Murungai"]),
        "entry_type": "Ayurveda",
        "category": "Nutritional Superfood / Multi-purpose",
        "botanical_name": "Moringa oleifera",
        "plant_family": "Moringaceae",
        "parts_used": "Leaves, pods, seeds, roots",
        "rasa": "Tikta (bitter), Katu (pungent)",
        "virya": "Ushna (hot)",
        "dosha_effect": "Balances Kapha and Vata",
        "traditional_uses": json.dumps(["Malnutrition","Lactation","Diabetes","Inflammation","Wound healing","Anaemia"]),
        "modern_evidence": "Gram for gram: 7x Vitamin C of oranges, 4x Calcium of milk, 4x Vitamin A of carrots, 2x protein of yogurt. Isothiocyanates: anti-inflammatory. Chlorogenic acid: hypoglycaemic.",
        "calories_per_100g": 64.0,
        "protein_g": 9.4,
        "carbs_g": 8.28,
        "fat_g": 1.4,
        "fiber_g": 2.0,
        "key_nutrients": json.dumps({"vitamin_C": "51.7mg", "calcium": "185mg", "iron": "4mg", "vitamin_A": "378mcg", "potassium": "337mg"}),
        "drug_interactions": json.dumps(["Thyroid medications (may alter thyroid function)","Antidiabetics (additive)","Antihypertensives (additive)","Warfarin (monitor INR)"]),
        "dose_adult": "Leaf powder: 5-10g/day. Leaf extract: 400-500mg BD",
        "dose_pediatric": "2-3g powder in food daily",
        "diet_category": "Nutritional supplement, Diabetic-friendly, Lactation support",
        "health_benefits": json.dumps(["Nutritional powerhouse","Anti-inflammatory","Hypoglycaemic","Galactagogue","Antioxidant","Antimicrobial"]),
    },
    {
        "name": "Holy Basil (Tulsi)",
        "local_names": json.dumps(["Tulsi","Holy Basil","Ocimum sanctum","Tulasi"]),
        "entry_type": "Ayurveda",
        "category": "Adaptogen / Antimicrobial",
        "botanical_name": "Ocimum sanctum / tenuiflorum",
        "parts_used": "Leaves, seeds, roots",
        "rasa": "Tikta (bitter), Katu (pungent)",
        "virya": "Ushna (hot)",
        "dosha_effect": "Balances Kapha and Vata",
        "traditional_uses": json.dumps(["Respiratory infections","Stress","Fever","Digestion","Immunity","Antimicrobial"]),
        "modern_evidence": "Eugenol: COX inhibitor (NSAID-like). Ursolic acid: anti-inflammatory. Adaptogenic: reduces cortisol. Antimicrobial against MRSA and Candida.",
        "drug_interactions": json.dumps(["Anticoagulants (eugenol — potentiates)","Antidiabetics (additive)","Antihypertensives (additive)","Barbiturates (may prolong sedation)"]),
        "dose_adult": "Leaves: 5-10g fresh daily. Tea: 5-10 leaves in boiling water BD. Extract: 300-600mg BD",
        "dose_pediatric": "2-5 leaves in warm water or honey",
        "diet_category": "Anti-inflammatory, Immune support, Adaptogen",
        "health_benefits": json.dumps(["Adaptogenic (stress relief)","Antimicrobial","Immune stimulant","Anti-inflammatory","Antioxidant","Respiratory support"]),
    },
    {
        "name": "Ginger (Zingiber)",
        "local_names": json.dumps(["Ginger","Adrak","Zingiber officinale","Ingber"]),
        "entry_type": "Ayurveda",
        "category": "Digestive / Anti-inflammatory / Antiemetic",
        "botanical_name": "Zingiber officinale",
        "plant_family": "Zingiberaceae",
        "parts_used": "Root (rhizome)",
        "rasa": "Katu (pungent), Madhura (sweet when dried)",
        "virya": "Ushna (hot)",
        "dosha_effect": "Balances Kapha and Vata",
        "traditional_uses": json.dumps(["Nausea/vomiting","Morning sickness","Indigestion","Arthritis","Cold/flu","Motion sickness"]),
        "modern_evidence": "10+ RCTs: superior to placebo for N&V of pregnancy (Cochrane 2014). Gingerols/shogaols: 5-HT3 antagonism + COX inhibition. Modest anti-inflammatory for OA.",
        "calories_per_100g": 80.0,
        "protein_g": 1.82,
        "carbs_g": 17.77,
        "fat_g": 0.75,
        "fiber_g": 2.0,
        "key_nutrients": json.dumps({"gingerols": "active", "potassium": "415mg", "manganese": "0.23mg"}),
        "drug_interactions": json.dumps(["Warfarin (potentiates anticoagulation — monitor INR)","Antiplatelet drugs (additive bleeding risk)","Antidiabetics (additive)","Nifedipine (may enhance)"]),
        "dose_adult": "1-2g fresh ginger or 250-500mg extract for nausea. Up to 4g/day anti-inflammatory.",
        "dose_pediatric": "500mg freshly grated or tea",
        "dose_geriatric": "1-2g/day; safe and beneficial",
        "safety_notes": "Generally very safe. High doses may cause GI irritation. Caution with anticoagulants.",
        "diet_category": "Digestive health, Anti-inflammatory, Antiemetic",
        "health_benefits": json.dumps(["Antiemetic","Anti-inflammatory","Digestive stimulant","Antioxidant","Antimicrobial","Analgesic"]),
    },
    {
        "name": "Garlic (Allium sativum)",
        "local_names": json.dumps(["Garlic","Lahsun","Rosun","Kraai thiam"]),
        "entry_type": "Ayurveda",
        "category": "Cardiovascular / Antimicrobial",
        "botanical_name": "Allium sativum",
        "plant_family": "Amaryllidaceae",
        "parts_used": "Bulb (cloves)",
        "rasa": "Katu (pungent), Tikta (bitter)",
        "virya": "Ushna (hot)",
        "dosha_effect": "Balances Kapha and Vata; may increase Pitta",
        "traditional_uses": json.dumps(["Hypertension","Hyperlipidaemia","Antimicrobial","Immune support","Atherosclerosis prevention"]),
        "modern_evidence": "Allicin: anti-hypertensive (3-5mmHg SBP reduction in meta-analysis), cholesterol lowering (modest), anti-platelet, antimicrobial against MRSA, anti-fungal.",
        "calories_per_100g": 149.0,
        "protein_g": 6.36,
        "carbs_g": 33.06,
        "fat_g": 0.5,
        "fiber_g": 2.1,
        "key_nutrients": json.dumps({"allicin": "active (created when crushed)", "selenium": "14.2mcg", "vitamin_C": "31.2mg", "manganese": "1.67mg"}),
        "drug_interactions": json.dumps(["Warfarin (potentiates — significant INR increase)","Antiplatelet drugs (additive)","HIV protease inhibitors (saquinavir — reduces levels)","Antihypertensives (additive)","Antidiabetics (additive)"]),
        "dose_adult": "1-2 raw cloves daily OR 600-1200mg aged garlic extract. Allicin-standardised: 10mg/day",
        "dose_pediatric": "Culinary amounts safe; supplements not well studied in children",
        "safety_notes": "Culinary doses safe. High dose supplements: GI irritation, breath odour, bleeding risk with anticoagulants. Crush garlic and wait 10 min before cooking to preserve allicin.",
        "diet_category": "Cardiac-friendly, Anti-inflammatory, Antimicrobial",
        "health_benefits": json.dumps(["Antihypertensive","Cholesterol lowering","Antiplatelet","Antimicrobial","Antioxidant","Immune stimulant"]),
    },

    # ─── VEGETABLES (12) ─────────────────────────────────────────────────────
    {
        "name": "Spinach",
        "local_names": json.dumps(["Spinach","Palak","Keerai","Épinard"]),
        "entry_type": "Vegetable",
        "category": "Leafy Green / Nutrient-dense",
        "botanical_name": "Spinacia oleracea",
        "calories_per_100g": 23.0,
        "protein_g": 2.86,
        "carbs_g": 3.63,
        "fat_g": 0.39,
        "fiber_g": 2.2,
        "key_nutrients": json.dumps({"vitamin_K": "483mcg (HIGH)", "folate": "194mcg", "iron": "2.71mg", "magnesium": "79mg", "vitamin_A": "469mcg", "calcium": "99mg"}),
        "indications": json.dumps(["Iron deficiency anaemia","Bone health","Folate deficiency","Eye health (lutein)"]),
        "contraindications": "Oxalate content (kidney stones, avoid in hyperoxaluria). HIGH Vitamin K — warfarin interaction.",
        "drug_interactions": json.dumps(["Warfarin (HIGH Vitamin K — maintain CONSISTENT intake; sudden increase can lower INR dramatically)","Iron supplements (oxalate reduces absorption)","Calcium supplements (oxalate binds calcium)"]),
        "dose_adult": "1-3 cups cooked/day; consistent intake important for warfarin patients",
        "glycemic_index": "Very Low (GI ~15)",
        "diet_category": "Diabetic-friendly, Cardiac-friendly, Weight management, Anaemia",
        "health_benefits": json.dumps(["Iron for anaemia","Bone health (Vit K)","Eye health (lutein/zeaxanthin)","Anti-cancer (antioxidants)","Brain health (folate)"]),
    },
    {
        "name": "Broccoli",
        "local_names": json.dumps(["Broccoli","Calabrese"]),
        "entry_type": "Vegetable",
        "category": "Cruciferous / Anti-cancer",
        "botanical_name": "Brassica oleracea var. italica",
        "calories_per_100g": 34.0,
        "protein_g": 2.82,
        "carbs_g": 6.64,
        "fat_g": 0.37,
        "fiber_g": 2.6,
        "key_nutrients": json.dumps({"vitamin_C": "89.2mg", "vitamin_K": "101.6mcg", "sulforaphane": "high (in sprouts)", "folate": "63mcg", "chromium": "high"}),
        "drug_interactions": json.dumps(["Warfarin (Vitamin K — consistent intake important)","Thyroid medications (large amounts of raw broccoli — goitrogenic, cook to reduce)"]),
        "diet_category": "Anti-cancer, Diabetic-friendly, Cardiac-friendly",
        "health_benefits": json.dumps(["Anti-cancer (sulforaphane)","Antioxidant","Bone health","Immune support","Detoxification","Anti-inflammatory"]),
        "glycemic_index": "Very Low (GI 10-15)",
    },
    {
        "name": "Sweet Potato",
        "local_names": json.dumps(["Sweet Potato","Shakarkand","Camote","Batata"]),
        "entry_type": "Vegetable",
        "category": "Complex Carbohydrate / Beta-carotene",
        "botanical_name": "Ipomoea batatas",
        "calories_per_100g": 86.0,
        "protein_g": 1.57,
        "carbs_g": 20.12,
        "fat_g": 0.05,
        "fiber_g": 3.0,
        "key_nutrients": json.dumps({"vitamin_A": "961mcg (beta-carotene)", "vitamin_C": "19.6mg", "potassium": "337mg", "manganese": "0.26mg"}),
        "drug_interactions": json.dumps(["Antidiabetics (monitor blood sugar — medium-high GI when boiled)","Warfarin (contains Vitamin K — minor)"]),
        "diet_category": "Diabetic-friendly (moderate), Cardiac-friendly, Weight management",
        "health_benefits": json.dumps(["Vitamin A (eye/immune health)","Antioxidant (beta-carotene)","Fibre for gut health","Potassium for BP","Energy (complex carbs)"]),
        "glycemic_index": "Medium (GI ~63 boiled; 94 baked — prefer boiled)",
    },
    {
        "name": "Bitter Melon (Karela)",
        "local_names": json.dumps(["Bitter Gourd","Karela","Bitter Melon","Ampalaya"]),
        "entry_type": "Vegetable",
        "category": "Anti-diabetic",
        "botanical_name": "Momordica charantia",
        "plant_family": "Cucurbitaceae",
        "rasa": "Tikta (bitter)",
        "virya": "Sheeta (cool)",
        "dosha_effect": "Balances Pitta and Kapha",
        "traditional_uses": json.dumps(["Diabetes","Malaria","HIV support (in vitro)","Skin diseases","Parasites"]),
        "modern_evidence": "Polypeptide-p (plant insulin), charantin, momordicin: GLUT4 upregulation + AMPK activation + alpha-glucosidase inhibition → hypoglycaemic. 4 meta-analyses: modest HbA1c reduction (~0.5%).",
        "calories_per_100g": 17.0,
        "protein_g": 1.0,
        "carbs_g": 3.7,
        "fat_g": 0.17,
        "fiber_g": 2.8,
        "key_nutrients": json.dumps({"vitamin_C": "84mg", "folate": "72mcg", "zinc": "0.8mg"}),
        "drug_interactions": json.dumps(["Antidiabetics (SIGNIFICANT additive hypoglycaemia — monitor closely, may need dose reduction)","Insulin (additive)","Cytochrome P450: CYP3A4 substrate (theoretical)"]),
        "dose_adult": "Fresh juice: 50-100mL once daily. Powder: 1-2g TDS. Vegetable: unlimited",
        "safety_notes": "Hypoglycaemia risk with antidiabetic medications. Avoid in G6PD deficiency (haemolysis). Avoid in pregnancy (emmenagogue).",
        "glycemic_index": "Very Low (GI ~5)",
        "diet_category": "Diabetic-friendly, Weight management, Anti-parasitic",
        "health_benefits": json.dumps(["Blood sugar lowering","Antioxidant","Anti-inflammatory","Antimicrobial","Liver protective"]),
    },
    {
        "name": "Fenugreek (Methi)",
        "local_names": json.dumps(["Fenugreek","Methi","Trigonella","Medhika"]),
        "entry_type": "Vegetable",
        "category": "Anti-diabetic / Galactagogue",
        "botanical_name": "Trigonella foenum-graecum",
        "parts_used": "Seeds, leaves",
        "rasa": "Tikta (bitter), Katu (pungent)",
        "virya": "Ushna (hot)",
        "dosha_effect": "Balances Kapha and Vata",
        "traditional_uses": json.dumps(["Diabetes","Lactation","Hyperlipidaemia","Testosterone support (male)","Digestion"]),
        "modern_evidence": "4-hydroxyisoleucine: insulin secretagogue + sensitiser. Soluble fibre (galactomannan): slows glucose absorption. Meta-analysis: HbA1c reduction ~0.85%. Galactagogue: prolactin stimulation.",
        "calories_per_100g": 323.0,
        "protein_g": 23.0,
        "carbs_g": 58.35,
        "fat_g": 6.41,
        "fiber_g": 24.6,
        "key_nutrients": json.dumps({"iron": "33.5mg", "magnesium": "191mg", "soluble_fiber": "high (galactomannan)"}),
        "drug_interactions": json.dumps(["Antidiabetics (additive — monitor blood glucose)","Warfarin (seeds contain coumarin compounds — monitor INR)","Iron supplements (antinutrients reduce absorption)"]),
        "dose_adult": "Seeds: 5-15g/day soaked overnight. Powder: 2-5g/day. Supplement: 500-1000mg extract BD",
        "safety_notes": "May cause flatulence. Maple syrup-like odour in urine/sweat. Avoid high doses in pregnancy (uterine stimulant).",
        "glycemic_index": "Low (GI ~18 for whole seeds)",
        "diet_category": "Diabetic-friendly, Lactation support, Cholesterol management",
        "health_benefits": json.dumps(["Blood sugar control","Cholesterol lowering","Lactation support","Testosterone support","Digestive health","Iron source"]),
    },
    {
        "name": "Drumstick (Moringa pods)",
        "local_names": json.dumps(["Drumstick","Sahjan ki phali","Murungakkai"]),
        "entry_type": "Vegetable",
        "category": "Nutritional Vegetable",
        "botanical_name": "Moringa oleifera (pods)",
        "calories_per_100g": 37.0,
        "protein_g": 2.1,
        "carbs_g": 8.53,
        "fat_g": 0.2,
        "fiber_g": 3.2,
        "key_nutrients": json.dumps({"vitamin_C": "141mg", "calcium": "30mg", "potassium": "461mg"}),
        "diet_category": "Diabetic-friendly, Nutritional supplement",
        "health_benefits": json.dumps(["High Vitamin C","Anti-inflammatory","Anti-diabetic","Bone health"]),
        "glycemic_index": "Low",
    },
    {
        "name": "Onion",
        "local_names": json.dumps(["Onion","Pyaz","Vengayam","Cebolla"]),
        "entry_type": "Vegetable",
        "category": "Cardiovascular / Antimicrobial",
        "botanical_name": "Allium cepa",
        "calories_per_100g": 40.0,
        "protein_g": 1.1,
        "carbs_g": 9.34,
        "fat_g": 0.1,
        "fiber_g": 1.7,
        "key_nutrients": json.dumps({"quercetin": "high", "chromium": "present", "vitamin_C": "7.4mg", "folic_acid": "19mcg"}),
        "drug_interactions": json.dumps(["Anticoagulants (quercetin — mild potentiation)","Antidiabetics (additive)"]),
        "diet_category": "Cardiac-friendly, Anti-inflammatory, Diabetic-friendly",
        "health_benefits": json.dumps(["Cardiovascular protection (quercetin)","Antimicrobial","Anti-inflammatory","Blood sugar control","Bone health (quercetin)"]),
        "glycemic_index": "Low (GI 10)",
    },
    {
        "name": "Beetroot",
        "local_names": json.dumps(["Beetroot","Chukandar","Beets"]),
        "entry_type": "Vegetable",
        "category": "Cardiovascular / Performance",
        "botanical_name": "Beta vulgaris",
        "calories_per_100g": 43.0,
        "protein_g": 1.61,
        "carbs_g": 9.96,
        "fat_g": 0.17,
        "fiber_g": 2.8,
        "key_nutrients": json.dumps({"nitrates": "high (250-300mg/100g)", "folate": "109mcg", "potassium": "325mg", "betacyanin": "antioxidant"}),
        "drug_interactions": json.dumps(["Antihypertensives (additive blood pressure lowering via nitrates)","Sildenafil/nitrates (additive hypotension)"]),
        "diet_category": "Cardiac-friendly, Athletic performance, Anaemia",
        "health_benefits": json.dumps(["Blood pressure lowering (dietary nitrate → NO)","Athletic performance","Anti-inflammatory","Liver protection","Folate source"]),
        "glycemic_index": "Medium (GI ~61 cooked; 35 raw)",
    },
    {
        "name": "Okra (Ladies Finger)",
        "local_names": json.dumps(["Okra","Ladies Finger","Bhindi","Vendaikkai"]),
        "entry_type": "Vegetable",
        "category": "Anti-diabetic / Digestive",
        "botanical_name": "Abelmoschus esculentus",
        "calories_per_100g": 33.0,
        "protein_g": 1.93,
        "carbs_g": 7.45,
        "fat_g": 0.19,
        "fiber_g": 3.2,
        "key_nutrients": json.dumps({"mucilage": "high", "vitamin_C": "23mg", "folate": "60mcg", "vitamin_K": "31.3mcg"}),
        "drug_interactions": json.dumps(["Metformin (mucilage may reduce absorption — 2h gap recommended)","Antidiabetics (additive)"]),
        "diet_category": "Diabetic-friendly, Digestive health",
        "health_benefits": json.dumps(["Blood sugar stabilisation (mucilage slows absorption)","Digestive health","Anti-oxidant","Cholesterol reduction","Folate source"]),
        "glycemic_index": "Very Low (GI ~20)",
    },
    {
        "name": "Bottle Gourd (Lauki)",
        "local_names": json.dumps(["Bottle Gourd","Lauki","Kaddu","Sorakkai"]),
        "entry_type": "Vegetable",
        "category": "Cardiac / Renal / Low-calorie",
        "botanical_name": "Lagenaria siceraria",
        "calories_per_100g": 14.0,
        "protein_g": 0.62,
        "carbs_g": 3.39,
        "fat_g": 0.02,
        "fiber_g": 0.5,
        "key_nutrients": json.dumps({"water": "96%", "vitamin_C": "10.1mg", "choline": "4.4mg"}),
        "drug_interactions": json.dumps(["Diuretics (additive fluid reduction)", "Antihypertensives (additive)"]),
        "safety_notes": "RAW/BITTER bottle gourd juice: TOXIC (cucurbitacins) — severe GI haemorrhage and death reported. Never drink raw bitter juice.",
        "diet_category": "Renal-friendly, Cardiac-friendly, Weight management, Diabetic-friendly",
        "health_benefits": json.dumps(["Extremely low calorie","High water content","Cooling effect","Kidney health","Cardiac health","Easy digestion"]),
        "glycemic_index": "Very Low",
    },
    {
        "name": "Tomato",
        "local_names": json.dumps(["Tomato","Tamatar","Thakkali"]),
        "entry_type": "Vegetable",
        "category": "Antioxidant / Cancer prevention",
        "botanical_name": "Solanum lycopersicum",
        "calories_per_100g": 18.0,
        "protein_g": 0.88,
        "carbs_g": 3.89,
        "fat_g": 0.2,
        "fiber_g": 1.2,
        "key_nutrients": json.dumps({"lycopene": "2573mcg (higher when cooked)", "vitamin_C": "13.7mg", "vitamin_K": "7.9mcg", "potassium": "237mg"}),
        "drug_interactions": json.dumps(["Warfarin (Vitamin K minor)","Tacrolimus (solanum family)"]),
        "diet_category": "Anti-cancer, Cardiac-friendly, Diabetic-friendly",
        "health_benefits": json.dumps(["Prostate cancer prevention (lycopene)","Antioxidant","Cardiovascular protection","Skin health","Anti-inflammatory"]),
        "glycemic_index": "Very Low (GI 15)",
    },
    {
        "name": "Carrot",
        "local_names": json.dumps(["Carrot","Gajar","Carotte"]),
        "entry_type": "Vegetable",
        "category": "Vision / Antioxidant",
        "botanical_name": "Daucus carota",
        "calories_per_100g": 41.0,
        "protein_g": 0.93,
        "carbs_g": 9.58,
        "fat_g": 0.24,
        "fiber_g": 2.8,
        "key_nutrients": json.dumps({"beta_carotene": "8285mcg (Vitamin A precursor)", "vitamin_K": "13.2mcg", "potassium": "320mg", "biotin": "6mcg"}),
        "drug_interactions": json.dumps(["Warfarin (Vitamin K — consistent intake)","Orlistat (reduces beta-carotene absorption)"]),
        "diet_category": "Diabetic-friendly, Eye health, Cardiac-friendly",
        "health_benefits": json.dumps(["Vision health (beta-carotene → Vit A)","Antioxidant","Immune support","Cancer prevention","Gut health (fibre)"]),
        "glycemic_index": "Low (GI ~35 raw; 47 cooked)",
    },

    # ─── FRUITS (12) ─────────────────────────────────────────────────────────
    {
        "name": "Banana",
        "local_names": json.dumps(["Banana","Kela","Kele","Plantain (unripe)"]),
        "entry_type": "Fruit",
        "category": "Energy / Potassium / Prebiotic",
        "botanical_name": "Musa acuminata",
        "calories_per_100g": 89.0,
        "protein_g": 1.09,
        "carbs_g": 22.84,
        "fat_g": 0.33,
        "fiber_g": 2.6,
        "key_nutrients": json.dumps({"potassium": "358mg (high)", "vitamin_B6": "0.37mg", "magnesium": "27mg", "resistant_starch": "high in unripe"}),
        "drug_interactions": json.dumps(["MAOIs (tyramine content — theoretical, low risk)","Warfarin (Vitamin K minor)","ACE inhibitors/ARBs (potassium — monitor K+ levels if eating large quantities)","K+ supplements (additive)"]),
        "dose_adult": "1-2 medium bananas/day recommended for potassium",
        "glycemic_index": "Medium (GI 51 ripe; 30 unripe — resistant starch)",
        "diet_category": "Athletic performance, Cardiac-friendly, Renal (watch K+ in CKD)",
        "health_benefits": json.dumps(["Potassium for heart health","Prebiotic (resistant starch)","Energy","Serotonin precursor (tryptophan)","Digestive health"]),
    },
    {
        "name": "Mango",
        "local_names": json.dumps(["Mango","Aam","Manga","Mango fruit"]),
        "entry_type": "Fruit",
        "category": "Antioxidant / Vitamin C and A",
        "botanical_name": "Mangifera indica",
        "calories_per_100g": 60.0,
        "protein_g": 0.82,
        "carbs_g": 14.98,
        "fat_g": 0.38,
        "fiber_g": 1.6,
        "key_nutrients": json.dumps({"vitamin_C": "36.4mg", "vitamin_A": "54mcg", "folate": "43mcg", "beta_carotene": "640mcg", "mangiferin": "anti-inflammatory polyphenol"}),
        "drug_interactions": json.dumps(["Warfarin (Vitamin K in mango leaves — fruit: minimal interaction)","Antidiabetics (sugar content — monitor)"]),
        "glycemic_index": "Medium (GI 51-56)",
        "diet_category": "Seasonal fruit, Diabetic (moderate portions)",
        "health_benefits": json.dumps(["Immune support (Vit C)","Eye health (Vit A)","Antioxidant (mangiferin)","Anti-cancer","Digestive enzymes (amylases)"]),
    },
    {
        "name": "Papaya",
        "local_names": json.dumps(["Papaya","Papita","Pawpaw","Papaye"]),
        "entry_type": "Fruit",
        "category": "Digestive / Antioxidant",
        "botanical_name": "Carica papaya",
        "calories_per_100g": 43.0,
        "protein_g": 0.47,
        "carbs_g": 10.82,
        "fat_g": 0.26,
        "fiber_g": 1.7,
        "key_nutrients": json.dumps({"vitamin_C": "61.8mg", "vitamin_A": "47mcg", "papain": "digestive enzyme (unripe)", "folate": "37mcg", "lycopene": "present"}),
        "drug_interactions": json.dumps(["Warfarin (potentiates significantly — monitor INR)","Antiplatelet drugs (papain antiplatelet activity)","Antidiabetics (additive)"]),
        "safety_notes": "Unripe papaya: high papain content — AVOID in pregnancy (uterine stimulant, abortifacient). Ripe papaya is safe.",
        "glycemic_index": "Low-Medium (GI 56-60)",
        "diet_category": "Digestive health, Immune support, Cardiac-friendly",
        "health_benefits": json.dumps(["Digestive enzyme (papain)","Antioxidant","Immune support","Anti-inflammatory","Wound healing","Dengue platelet support (papaya leaf juice — studied)"]),
    },
    {
        "name": "Pomegranate",
        "local_names": json.dumps(["Pomegranate","Anaar","Anar","Granada"]),
        "entry_type": "Fruit",
        "category": "Cardiovascular / Antioxidant",
        "botanical_name": "Punica granatum",
        "calories_per_100g": 83.0,
        "protein_g": 1.67,
        "carbs_g": 18.7,
        "fat_g": 1.17,
        "fiber_g": 4.0,
        "key_nutrients": json.dumps({"punicalagins": "high antioxidant (3x red wine)", "ellagic_acid": "present", "vitamin_C": "10.2mg", "folate": "38mcg", "potassium": "236mg"}),
        "drug_interactions": json.dumps(["Warfarin (potentiates — significant case reports; monitor INR)","Antihypertensives (additive)","Statins (inhibits CYP3A4 — pomegranate juice)","Antidiabetics (additive)"]),
        "dose_adult": "150-250mL juice/day OR 1 medium fruit",
        "glycemic_index": "Low-Medium (GI 53)",
        "diet_category": "Cardiac-friendly, Anti-inflammatory, Diabetic-friendly",
        "health_benefits": json.dumps(["Powerful antioxidant","Anti-atherosclerotic","Blood pressure lowering","Anti-cancer","Anti-inflammatory","Prostate health"]),
    },
    {
        "name": "Guava",
        "local_names": json.dumps(["Guava","Amrood","Peru","Jambu batu"]),
        "entry_type": "Fruit",
        "category": "Vitamin C / Anti-diabetic",
        "botanical_name": "Psidium guajava",
        "calories_per_100g": 68.0,
        "protein_g": 2.55,
        "carbs_g": 14.32,
        "fat_g": 0.95,
        "fiber_g": 5.4,
        "key_nutrients": json.dumps({"vitamin_C": "228mg (highest of common fruits)", "lycopene": "5200mcg (pink guava)", "potassium": "417mg", "folate": "49mcg"}),
        "drug_interactions": json.dumps(["Antidiabetics (additive blood sugar lowering)","Warfarin (minor)"]),
        "glycemic_index": "Low (GI 12-24)",
        "diet_category": "Diabetic-friendly, Immune support, Weight management",
        "health_benefits": json.dumps(["Highest Vitamin C of common fruits","Anti-diabetic","Antioxidant (lycopene)","Cardiovascular","Digestive health (fibre)"]),
    },
    {
        "name": "Apple",
        "local_names": json.dumps(["Apple","Seb","Saebu","Pomme"]),
        "entry_type": "Fruit",
        "category": "General Health / Prebiotic",
        "botanical_name": "Malus domestica",
        "calories_per_100g": 52.0,
        "protein_g": 0.26,
        "carbs_g": 13.81,
        "fat_g": 0.17,
        "fiber_g": 2.4,
        "key_nutrients": json.dumps({"quercetin": "high (peel)", "pectin": "soluble fibre", "vitamin_C": "4.6mg", "vitamin_K": "2.2mcg"}),
        "drug_interactions": json.dumps(["Some drug transport (quercetin inhibits OATPs — may reduce fexofenadine/statin levels if large amounts)","Warfarin (minor)"]),
        "glycemic_index": "Low (GI 36)",
        "diet_category": "Diabetic-friendly, Cardiac-friendly, Weight management",
        "health_benefits": json.dumps(["Gut health (pectin prebiotic)","Quercetin anti-inflammatory","Cholesterol lowering","Cancer prevention","Brain health"]),
    },
    {
        "name": "Lemon",
        "local_names": json.dumps(["Lemon","Nimbu","Limon","Citron"]),
        "entry_type": "Fruit",
        "category": "Vitamin C / Alkalising",
        "botanical_name": "Citrus limon",
        "calories_per_100g": 29.0,
        "protein_g": 1.1,
        "carbs_g": 9.32,
        "fat_g": 0.3,
        "fiber_g": 2.8,
        "key_nutrients": json.dumps({"vitamin_C": "53mg", "citric_acid": "high (5-7%)", "limonene": "anticancer", "hesperidin": "flavonoid"}),
        "drug_interactions": json.dumps(["Iron supplements (enhances non-haem iron absorption — beneficial)","Statins (unlike grapefruit, lemon does NOT inhibit CYP3A4)","Aluminium antacids (may increase absorption)"]),
        "diet_category": "Immune support, Alkalising, Weight management, Renal (prevents kidney stones)",
        "health_benefits": json.dumps(["Immune support (Vit C)","Kidney stone prevention (citrate)","Digestion aid","Antioxidant","Alkalising effect","Skin health"]),
        "glycemic_index": "Very Low (GI ~20)",
    },
    {
        "name": "Watermelon",
        "local_names": json.dumps(["Watermelon","Tarbooz","Tarbuj","Semangka"]),
        "entry_type": "Fruit",
        "category": "Hydration / Cardiovascular",
        "botanical_name": "Citrullus lanatus",
        "calories_per_100g": 30.0,
        "protein_g": 0.61,
        "carbs_g": 7.55,
        "fat_g": 0.15,
        "fiber_g": 0.4,
        "key_nutrients": json.dumps({"lycopene": "4532mcg (highest fruit)", "citrulline": "high (precursor to arginine → NO)", "vitamin_C": "8.1mg", "water": "92%"}),
        "drug_interactions": json.dumps(["Antihypertensives (citrulline → arginine → NO → additive BP lowering)","Sildenafil (additive vasodilatation — caution)"]),
        "glycemic_index": "Medium-High (GI 72 but low glycaemic load due to water content)",
        "diet_category": "Hydration, Cardiac-friendly, Athletic performance",
        "health_benefits": json.dumps(["Hydration (92% water)","Lycopene (anti-cancer, cardiac)","Citrulline → athletic performance","Blood pressure","Kidney health"]),
    },
    {
        "name": "Grapes",
        "local_names": json.dumps(["Grapes","Angur","Raisins (dried)","Uvas"]),
        "entry_type": "Fruit",
        "category": "Cardiovascular / Antioxidant",
        "botanical_name": "Vitis vinifera",
        "calories_per_100g": 69.0,
        "protein_g": 0.72,
        "carbs_g": 18.1,
        "fat_g": 0.16,
        "fiber_g": 0.9,
        "key_nutrients": json.dumps({"resveratrol": "high in skin/seeds", "quercetin": "present", "vitamin_K": "14.6mcg", "potassium": "191mg"}),
        "drug_interactions": json.dumps(["Warfarin (Vitamin K — consistent intake)","Statins (grape SEED extract may inhibit CYP3A4)","Antidiabetics (sugar content)"]),
        "glycemic_index": "Low-Medium (GI 53)",
        "diet_category": "Cardiac-friendly, Anti-inflammatory",
        "health_benefits": json.dumps(["Resveratrol (cardiovascular, anti-ageing)","Antioxidant","Anti-inflammatory","Memory (resveratrol)","Cancer prevention"]),
    },
    {
        "name": "Coconut",
        "local_names": json.dumps(["Coconut","Nariyal","Thengai","Kelapa"]),
        "entry_type": "Fruit",
        "category": "MCT Source / Tropical",
        "botanical_name": "Cocos nucifera",
        "calories_per_100g": 354.0,
        "protein_g": 3.33,
        "carbs_g": 15.23,
        "fat_g": 33.49,
        "fiber_g": 9.0,
        "key_nutrients": json.dumps({"MCT": "50-60% of fat (lauric acid)", "manganese": "1.5mg", "copper": "0.43mg", "electrolytes": "coconut water"}),
        "drug_interactions": json.dumps(["Statins (coconut oil raises LDL — caution with lipid-lowering therapy)","Insulin (coconut sugar has lower GI vs refined)"]),
        "safety_notes": "Coconut water: excellent oral rehydration. Coconut oil high in saturated fat — debate ongoing on cardiovascular effects (raises both LDL and HDL).",
        "diet_category": "Ketogenic, Tropical nutrition, Rehydration (coconut water)",
        "health_benefits": json.dumps(["MCT (ketone energy)","Electrolyte replenishment (water)","Antimicrobial (lauric acid)","Skin/hair health (oil)","Digestive fibre"]),
        "glycemic_index": "Low (coconut flour GI ~51; coconut water GI ~54)",
    },
    {
        "name": "Jamun (Black Plum)",
        "local_names": json.dumps(["Jamun","Java Plum","Black Plum","Jambolan"]),
        "entry_type": "Fruit",
        "category": "Anti-diabetic / Antioxidant",
        "botanical_name": "Syzygium cumini",
        "calories_per_100g": 60.0,
        "protein_g": 0.72,
        "carbs_g": 14.0,
        "fat_g": 0.23,
        "fiber_g": 0.6,
        "key_nutrients": json.dumps({"anthocyanins": "high", "jamboline": "anti-diabetic glycoside", "ellagic_acid": "present", "vitamin_C": "14.3mg"}),
        "drug_interactions": json.dumps(["Antidiabetics (SIGNIFICANT additive hypoglycaemia — monitor closely)","Insulin (additive)"]),
        "dose_adult": "Seeds: 5-10g powder daily (anti-diabetic use). Fresh fruit: seasonal consumption",
        "safety_notes": "Seeds have strongest anti-diabetic effect (jamboline). May cause constipation in excess. Not for children <5 years.",
        "glycemic_index": "Very Low (GI ~25)",
        "diet_category": "Diabetic-friendly, Antioxidant",
        "health_benefits": json.dumps(["Blood sugar control (jamboline)","Antioxidant (anthocyanins)","Dental health (astringent)","Anti-diarrhoeal","Spleen health"]),
    },

    # ─── SPICES / FOODS (11) ──────────────────────────────────────────────────
    {
        "name": "Black Pepper (Piper nigrum)",
        "local_names": json.dumps(["Black Pepper","Kali Mirch","Milagu","Poivre noir"]),
        "entry_type": "Spice",
        "category": "Bioavailability Enhancer / Digestive",
        "botanical_name": "Piper nigrum",
        "key_nutrients": json.dumps({"piperine": "5-9%", "manganese": "12.75mg", "vitamin_K": "163.7mcg", "iron": "9.71mg"}),
        "traditional_uses": json.dumps(["Bioavailability enhancer (piperine)","Digestive stimulant","Anti-inflammatory","Antimicrobial"]),
        "modern_evidence": "Piperine inhibits intestinal metabolic enzymes and P-glycoprotein → increases bioavailability of many drugs and nutraceuticals (curcumin by 2000%, selenium, B vitamins).",
        "drug_interactions": json.dumps(["Phenytoin (increases levels — significant)","Propranolol (increases bioavailability)","Theophylline (increases levels)","Rifampicin (increases levels)","Any drug in high-pepper meal — may alter absorption"]),
        "safety_notes": "Culinary doses safe. High medicinal piperine doses with narrow TI drugs (phenytoin, warfarin, digoxin) may alter levels significantly.",
        "diet_category": "Digestive aid, Bioavailability enhancer",
        "health_benefits": json.dumps(["Bioavailability enhancer","Anti-inflammatory","Antioxidant","Digestive stimulant","Antimicrobial"]),
    },
    {
        "name": "Cinnamon (Dalchini)",
        "local_names": json.dumps(["Cinnamon","Dalchini","Ilayangam","Canela"]),
        "entry_type": "Spice",
        "category": "Anti-diabetic / Antimicrobial",
        "botanical_name": "Cinnamomum verum (Ceylon) / cassia (Chinese)",
        "key_nutrients": json.dumps({"cinnamaldehyde": "active compound", "coumarin": "high in cassia (hepatotoxic at high doses)", "manganese": "17.5mg"}),
        "traditional_uses": json.dumps(["Diabetes","High cholesterol","Anti-inflammatory","Antimicrobial","Digestive"]),
        "modern_evidence": "Meta-analysis (13 RCTs): HbA1c reduction ~0.16%. Improves insulin sensitivity. Cinnamaldehyde: GLUT4 upregulation. PREFER Ceylon cinnamon (low coumarin) over Cassia (hepatotoxic coumarin).",
        "drug_interactions": json.dumps(["Antidiabetics (additive hypoglycaemia)","Anticoagulants (coumarin content — Cassia variety)","Antihypertensives (additive)"]),
        "dose_adult": "1-4g Ceylon cinnamon powder/day OR 120-360mg aqueous extract. AVOID Cassia >1g/day (coumarin toxicity).",
        "safety_notes": "Ceylon: safe. Cassia: contains coumarin (hepatotoxic >2g/day). Do not use Cassia medicinally.",
        "diet_category": "Diabetic-friendly, Cholesterol management",
        "health_benefits": json.dumps(["Blood sugar control","Cholesterol lowering","Antimicrobial","Anti-inflammatory","Antioxidant"]),
    },
    {
        "name": "Honey",
        "local_names": json.dumps(["Honey","Shahad","Madhu","Mel"]),
        "entry_type": "Food",
        "category": "Natural Sweetener / Antimicrobial",
        "calories_per_100g": 304.0,
        "carbs_g": 82.4,
        "key_nutrients": json.dumps({"hydrogen_peroxide": "antimicrobial", "methylglyoxal": "manuka honey", "antioxidants": "flavonoids, phenolic acids", "enzyme_activity": "diastase, invertase"}),
        "traditional_uses": json.dumps(["Wound healing","Cough","Antimicrobial","Antioxidant","Sleep aid"]),
        "modern_evidence": "Cochrane: honey as good as dextromethorphan for children's cough. Medical-grade Manuka honey (UMF 10+): FDA cleared for wounds. NOT suitable for infants <1 year (botulism spores).",
        "drug_interactions": json.dumps(["Antidiabetics (raises blood sugar — monitor)","Warfarin (flavonoids — minor interaction)"]),
        "safety_notes": "ABSOLUTELY CONTRAINDICATED in infants <1 year (Clostridium botulinum spores). Diabetics: use sparingly. Dental caries risk with excess use.",
        "dose_adult": "1-2 tsp/day as supplement. Wound care: topical MHC or medical-grade only",
        "diet_category": "Natural sweetener, Cough relief, Wound healing",
        "health_benefits": json.dumps(["Cough suppression","Wound healing","Antimicrobial","Antioxidant","Sleep support","Sore throat relief"]),
    },
    {
        "name": "Green Tea",
        "local_names": json.dumps(["Green Tea","Chai","Matcha","Sencha"]),
        "entry_type": "Food",
        "category": "Antioxidant / Metabolic",
        "botanical_name": "Camellia sinensis",
        "calories_per_100g": 1.0,
        "key_nutrients": json.dumps({"EGCG": "epigallocatechin gallate (most active catechin)", "L-theanine": "amino acid — calming alertness", "caffeine": "30-50mg/cup", "fluoride": "dental health"}),
        "traditional_uses": json.dumps(["Antioxidant","Weight management","Cancer prevention","Brain health","Cardiovascular"]),
        "modern_evidence": "EGCG: most studied polyphenol. Meta-analyses: modest weight loss (1.5kg), LDL reduction, BP reduction, T2DM risk. Neuroprotection: Parkinson's/Alzheimer's (epidemiological). Cancer: insufficient evidence.",
        "drug_interactions": json.dumps(["Warfarin (Vitamin K in leaves; EGCG antiplatelet — monitor INR)","Iron supplements (catechins reduce non-haem iron absorption — 2h gap)","Statins (EGCG inhibits transporter — monitor)","Nadolol (reduces levels significantly)","Clozapine (inhibits CYP1A2 clearance)"]),
        "dose_adult": "3-5 cups/day. EGCG supplement: 200-400mg/day (avoid fasting — hepatotoxicity risk)",
        "safety_notes": "EGCG supplements on empty stomach: hepatotoxicity risk (multiple cases). Drink as tea rather than high-dose supplements. Pregnancy: limit caffeine <200mg/day.",
        "diet_category": "Antioxidant, Weight management, Cardiac-friendly",
        "health_benefits": json.dumps(["Antioxidant (EGCG)","Metabolic (weight management)","Cardiovascular","Neuroprotection","Anti-cancer (possible)","Dental health (fluoride)"]),
    },
    {
        "name": "Flaxseeds (Alsi)",
        "local_names": json.dumps(["Flaxseeds","Alsi","Linseed","Lin"]),
        "entry_type": "Food",
        "category": "Omega-3 / Fibre / Phytoestrogen",
        "botanical_name": "Linum usitatissimum",
        "calories_per_100g": 534.0,
        "protein_g": 18.29,
        "carbs_g": 28.88,
        "fat_g": 42.16,
        "fiber_g": 27.3,
        "key_nutrients": json.dumps({"ALA_omega3": "22.8g (highest plant ALA)", "lignans": "phytoestrogens (800x more than other foods)", "soluble_fiber": "mucilage high"}),
        "drug_interactions": json.dumps(["All oral medications (mucilage gel — take medications 2h before or after)","Anticoagulants (omega-3 antiplatelet — monitor INR)","Antidiabetics (additive blood sugar lowering)","Hormonal therapies (phytoestrogen activity)"]),
        "dose_adult": "1-2 tbsp ground flaxseeds/day (must grind — whole seeds pass undigested)",
        "safety_notes": "MUST be ground. Large doses with inadequate fluid can cause bowel obstruction. Phytoestrogen: caution in oestrogen-sensitive cancers.",
        "diet_category": "Cardiac-friendly, Diabetic-friendly, Women's health, Constipation",
        "health_benefits": json.dumps(["Omega-3 ALA (anti-inflammatory, cardiac)","Phytoestrogen (menopausal symptoms)","Cholesterol lowering","Constipation relief","Cancer prevention (lignans)"]),
    },
    {
        "name": "Oats",
        "local_names": json.dumps(["Oats","Jaee","Avena","Oatmeal"]),
        "entry_type": "Food",
        "category": "Complex Carbohydrate / Cholesterol-lowering",
        "botanical_name": "Avena sativa",
        "calories_per_100g": 389.0,
        "protein_g": 16.89,
        "carbs_g": 66.27,
        "fat_g": 6.9,
        "fiber_g": 10.6,
        "key_nutrients": json.dumps({"beta_glucan": "3-4g/100g (cholesterol-lowering, glucose-slowing)", "avenanthramides": "antioxidant anti-inflammatory", "manganese": "3.63mg", "thiamine": "0.76mg"}),
        "drug_interactions": json.dumps(["Antidiabetics (beta-glucan slows glucose absorption — beneficial, monitor)","Warfarin (minor Vitamin K)"]),
        "dose_adult": "40-80g dry oats/day (3g beta-glucan/day FDA-approved for cholesterol reduction)",
        "diet_category": "Diabetic-friendly (low GI), Cardiac-friendly, Cholesterol management, Weight management",
        "health_benefits": json.dumps(["LDL cholesterol reduction (beta-glucan — FDA approved claim)","Blood sugar regulation","Satiety (weight management)","Gut microbiome (prebiotic)","Iron and B vitamins"]),
        "glycemic_index": "Low-Medium (GI 55 rolled oats; 42 steel-cut)",
    },
    {
        "name": "Lentils (Dal)",
        "local_names": json.dumps(["Lentils","Dal","Masoor","Dhal","Lenticchie"]),
        "entry_type": "Food",
        "category": "Plant Protein / Iron / Folate",
        "calories_per_100g": 116.0,
        "protein_g": 9.02,
        "carbs_g": 20.13,
        "fat_g": 0.38,
        "fiber_g": 7.9,
        "key_nutrients": json.dumps({"folate": "181mcg (high)", "iron": "3.3mg", "potassium": "369mg", "resistant_starch": "high", "protein": "plant-based complete AA with rice"}),
        "drug_interactions": json.dumps(["Iron supplements (phytic acid reduces absorption — Vitamin C enhances)","MAOIs (tyramine — low risk, not significant in cooked lentils)"]),
        "diet_category": "Diabetic-friendly, Cardiac-friendly, Renal (watch K+ and phosphorus in advanced CKD), Weight management",
        "health_benefits": json.dumps(["Plant protein","Folate (pregnancy essential)","Iron (anaemia prevention)","Blood sugar regulation","Gut health","Cholesterol lowering"]),
        "glycemic_index": "Low (GI 21-30)",
    },
]


def seed_ayurveda():
    conn = sqlite3.connect(DB_PATH, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()
    inserted = 0
    skipped = 0

    COLUMNS = [
        "name","local_names","entry_type","category","botanical_name","plant_family","parts_used",
        "rasa","virya","vipaka","dosha_effect","traditional_uses","modern_evidence",
        "indications","contraindications","calories_per_100g","protein_g","carbs_g","fat_g",
        "fiber_g","key_nutrients","drug_interactions","interactions_detail","dose_adult",
        "dose_pediatric","dose_geriatric","preparation","safety_notes","glycemic_index",
        "diet_category","health_benefits",
    ]

    for item in AYURVEDA_DATA:
        row = {c: item.get(c) for c in COLUMNS}
        ph = ", ".join(["?"] * len(COLUMNS))
        col_str = ", ".join(COLUMNS)
        values = [row[c] for c in COLUMNS]
        try:
            cur.execute(f"INSERT OR IGNORE INTO ayurveda_diet ({col_str}) VALUES ({ph})", values)
            if cur.rowcount > 0:
                inserted += 1
                log.info("  ✅ %s", item["name"])
            else:
                skipped += 1
        except Exception as e:
            log.error("  ❌ %s: %s", item.get("name","?"), e)

    conn.commit()
    conn.close()
    log.info("\n📊 Ayurveda/Diet — Inserted: %d | Skipped: %d | Total: %d",
             inserted, skipped, len(AYURVEDA_DATA))


if __name__ == "__main__":
    seed_ayurveda()
